config/routes.rb
Rails.application.routes.draw do
  resources :blog_posts
  resources :users
  get '/about', to: 'pages#about'
  get '/sample_blog_post', to: 'pages#sample_blog_post'
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  belongs_to :user

  validates :title, length: { maximum: 50 }, presence: true, uniqueness: true
  validates :summary, length: { maximum: 150 }, presence: true
  validates :content, presence: true
  validates :title_image_url, presence: false
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blog_posts

  validates :name, length: { maximum: 45 }, presence: true, uniqueness: true
  validates :email, length: { maximum: 45 }, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
    @user ||= User.all
  end

  # GET /blog_posts/1/edit
  def edit
    @user ||= User.all
    @user_selected = @blog_post.user
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    @user ||= User.all
    @user_selected = @blog_post.user
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :summary, :content, :user_id, :title_image_url)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def sample_blog_post
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog_posts/_form.html.erb
 <!-- Page Header -->
    <header class="masthead" style="background-image: url(<%= asset_path 'home-bg.jpg' %>)">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>Clean Blog</h1>
              <span class="subheading">A Blog about Anything</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <hr><%= form_with(model: blog_post, local: true) do |form| %>
  <% if blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-md-12">
    <%= form.label :title %>
    <%= form.text_field :title, :class=>"form-control" %>
  </div>

  <div class="form-group col-md-12">
    <%= form.label :summary %>
    <%= form.text_field :summary, :class=>"form-control" %>
  </div>

  <div class="form-group col-md-12">
    <%= form.label :content %>
    <%= form.text_area :content, :class=>"form-control" %>
  </div>

  <div class="form-group col-md-12">
    <%= form.label :user_id %>
    <%= select_tag 'blog_post[user_id]', options_for_select(@user.collect{ |u| [u.name, u.id] }, :selected => @user_selected.id), :class => "form-control"%>
  </div>

  <div class="form-group col-md-12">
    <%= form.label :title_image_url %>
    <%= form.text_field :title_image_url, :class=>"form-control" %>
  </div>

  <div class="form-group col-md-12">
    <%= form.submit :class=>"btn btn-primary"%>
  </div>
<% end %>
          <hr>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form', blog_post: @blog_post %>

<%= link_to 'Show', @blog_post,  :class=>"btn btn-primary" %> |
<%= link_to 'Back', blog_posts_path, :class=>"btn btn-secondary" %>

app/views/blog_posts/index.html.erb
 <!-- Page Header -->
    <header class="masthead" style="background-image: url(<%= asset_path 'home-bg.jpg' %>)">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>Blog Post</h1>
              <span class="subheading">A Blog about Anything</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <%= link_to 'New Blog Post', new_blog_post_path, :class=>"btn btn-primary float-right mb-2"%>
        </br>
        <hr>
        <table class="table table-striped" border="1"">
          <thead class="thead-dark">
            <tr>
              <th>Title</th>
              <th>Summary</th>
              <th>User</th>
              <th colspan="3" class="text-center">Action</th>
            </tr>
          </thead>

          <tbody>
            <% @blog_posts.each do |blog_post| %>
              <tr>
                <td><%= blog_post.title%></td>
                <td><%= blog_post.summary %></td>
                <td><%= blog_post.user.name %></td>
                <td><%= link_to 'Show', blog_post_path(blog_post), :class=>"btn btn-primary float-right" %></td>
                <td><%= link_to 'Edit', edit_blog_post_path(blog_post), :class=>"btn btn-warning float-right"%></td>
                <td><%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger float-right"%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <br>
      </div>
    </div>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form', blog_post: @blog_post %>

<%= link_to 'Back', blog_posts_path, :class=>"btn btn-secondary"%>

app/views/blog_posts/show.html.erb
 <!-- Page Header -->
  <% if @blog_post.title_image_url.present? %>
    <header class="masthead" style="background-image: url(<%= @blog_post.title_image_url %>)">
 <% else %>
  <header class="masthead" style="background-image: url(<%= asset_path 'home-bg.jpg' %>)">
<% end%>
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1><%= @blog_post.title %></h1>
              <span class="subheading"><%= @blog_post.summary %></span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <% if notice.present? %>
          <p id="notice" class="alert alert-success"><%= notice %></p>
          <% end %>
          <p>
            <%= @blog_post.content %>
          </p>

          <p>
            <%= @blog_post.user.name %>
          </p>

          <%= link_to 'Edit', edit_blog_post_path(@blog_post), :class=>"btn btn-primary" %> |
          <%= link_to 'Back', blog_posts_path, :class=>"btn btn-secondary" %>
      </div>
    </div>

    <hr>

app/views/layouts/_footer.html.erb
 <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Your Website 2018</p>
          </div>
        </div>
      </div>
    </footer>

app/views/layouts/_navigate.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "Homepage", root_path, :class => "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "About", about_path, :class => "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Blog Post", blog_posts_path, :class => "nav-link" %>
            </li>
            <li class="nav-item">
            <%= link_to 'User', users_path, :class => "nav-link" %>
          </li>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <%= render 'layouts/navigate' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
    <!-- Page Header -->
    <header class="masthead" style="background-image: url(<%= asset_path'about-bg.jpg' %>)">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1>About Me</h1>
              <span class="subheading">This is what I do.</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
        </div>
      </div>
    </div>

    <hr>

app/views/pages/home.html.erb
    <!-- Page Header -->
    <header class="masthead" style="background-image: url(<%= asset_path 'home-bg.jpg' %>)">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>Clean Blog</h1>
              <span class="subheading">A Blog about Anything</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-preview">
            <a href="post.html">
              <h2 class="post-title">
                Man must explore, and this is exploration at its greatest
              </h2>
              <h3 class="post-subtitle">
                Problems look mighty small from 150 miles up
              </h3>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Start Bootstrap</a>
              on September 24, 2018</p>
          </div>
          <hr>
          <div class="post-preview">
            <a href="post.html">
              <h2 class="post-title">
                I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
              </h2>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Start Bootstrap</a>
              on September 18, 2018</p>
          </div>
          <hr>
          <div class="post-preview">
            <a href="post.html">
              <h2 class="post-title">
                Science has not yet mastered prophecy
              </h2>
              <h3 class="post-subtitle">
                We predict too much for the next year and yet far too little for the next ten.
              </h3>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Start Bootstrap</a>
              on August 24, 2018</p>
          </div>
          <hr>
          <div class="post-preview">
            <a href="post.html">
              <h2 class="post-title">
                Failure is not an option
              </h2>
              <h3 class="post-subtitle">
                Many say exploration is part of our destiny, but it’s actually our duty to future generations.
              </h3>
            </a>
            <p class="post-meta">Posted by
              <a href="#">Start Bootstrap</a>
              on July 8, 2018</p>
          </div>
          <hr>
          <!-- Pager -->
          <div class="clearfix">
            <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
          </div>
        </div>
      </div>
    </div>

    <hr>

app/views/pages/sample_blog_post.html.erb
    <!-- Page Header -->
    <header class="masthead" style="background-image: url(<%= asset_path'post-sample-image.jpg' %>)">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading">
              <h1>Man must explore, and this is exploration at its greatest</h1>
              <h2 class="subheading">Problems look mighty small from 150 miles up</h2>
              <span class="meta">Posted by
                <a href="#">Start Bootstrap</a>
                on August 24, 2018</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Post Content -->
    <article>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>

            <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>

            <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>

            <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>

            <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>

            <h2 class="section-heading">The Final Frontier</h2>

            <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

            <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

            <blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>

            <p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.</p>

            <h2 class="section-heading">Reaching for the Stars</h2>

            <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.</p>

            <a href="#">
              <img class="img-fluid" src=<%= asset_path'post-sample-image.jpg' %> alt="">
            </a>
            <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>

            <p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>

            <p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.</p>

            <p>Placeholder text by
              <a href="http://spaceipsum.com/">Space Ipsum</a>. Photographs by
              <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>.</p>
          </div>
        </div>
      </div>
    </article>

    <hr>

app/views/users/_form.html.erb
 <!-- Page Header -->
    <header class="masthead" style="background-image: url(<%= asset_path 'home-bg.jpg' %>)">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>Clean Blog</h1>
              <span class="subheading">A Blog about Anything</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <%= form_with(model: user, local: true) do |form| %>
          <% if user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

              <ul>
              <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group col-md-6"">
            <%= form.label :name %>
            <%= form.text_field :name, :class=>"form-control" %>
          </div>

          <div class="form-group col-md-6">
            <%= form.label :email %>
            <%= form.text_field :email, :class=>"form-control" %>
          </div>

          <div class="fform-group col-md-6">
            <%= form.submit :class=>"btn btn-primary" %>
          </div>
        </br>
        <% end %>
      </div>
    </div>

    <hr>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user, :class=>"btn btn-primary" %> |
<%= link_to 'Back', users_path, :class=>"btn btn-secondary" %>

app/views/users/index.html.erb
    <!-- Page Header -->
    <header class="masthead" style="background-image: url(<%= asset_path 'contact-bg.jpg' %>)">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>Clean Blog</h1>
              <span class="subheading">A Blog about Anything</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container ">
      <div class="row">
          <%= link_to 'New User', new_user_path,:class=>"btn btn-primary float-right mb-2" %>
          <hr>
          <table class="table table-striped" border="1"">
            <thead class="thead-dark">
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th colspan="3" class="text-center">Action</th>
              </tr>
            </thead>

              <tbody>
                <% @users.each do |user| %>
                  <tr>
                    <td><%= user.name %></td>
                    <td><%= user.email %></td>
                    <td><%= link_to 'Show', user_path(user), :class=>"btn btn-primary float-right" %></td>
                    <td><%= link_to 'Edit', edit_user_path(user), :class=>"btn btn-warning float-right" %></td>
                    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger float-right" %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>

            <br>

        </div>
      </div>
    </div>

    <hr>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path, :class=>"btn btn-secondary"%>

app/views/users/show.html.erb
    <!-- Page Header -->


    <header class="masthead" style="background-image: url(<%= asset_path 'home-bg.jpg' %>)">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>Clean Blog</h1>
              <span class="subheading">A Blog about Anything</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->

    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <% if notice.present? %>
            <p id="notice" class="alert alert-success"><%= notice %></p>
          <% end %>

          <p class="font-weight-bold">
            <strong>Name:</strong>
            <%= @user.name %>
          </p>

          <p class="font-weight-normal">
            <strong>Email:</strong>
            <%= @user.email %>
          </p>

          <%= link_to 'Edit', edit_user_path(@user), :class=>"btn btn-primary" %> |
          <%= link_to 'Back', users_path, :class=>"btn btn-secondary"%>
        </div>
      </div>
    </div>